version: '3'

services:
  etcd:
    image: bitnami/etcd:3.5
    container_name: etcd
    user: "1000:1000"  # wuzhisong 用户的 UID 和 GID
    ports:
      - "3379:2379"
      - "3380:2380"
    environment:
      - ETCD_ENABLE_V2=true
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://172.16.240.24:3379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_NAME=etcd
    volumes:
      - ./components/etcd/data:/bitnami/etcd/data
      - ./components/etcd/logs:/bitnami/etcd/logs
    networks:
      easy-chat:

  redis:
    image: redis:alpine3.18
    ports:
      - 16379:6379
    container_name: redis
    volumes:
      - ./components/redis/data:/data
      - ./components/redis/config/redis.conf:/usr/local/redis/config/redis.conf
    environment:
      TZ: Asia/Shanghai
    restart: always
    networks:
      easy-chat:
    command: redis-server --requirepass easy-chat --appendonly yes
    user: "1000:1000"  # 添加当前用户的 UID 和 GID

  mysql:
    image: mysql:8.0
    ports:
      - 13306:3306
    container_name: mysql
    volumes:
      - ./components/mysql/data:/var/lib/mysql
      - /etc/localtime:/etc/localtime
    environment:
      MYSQL_ROOT_PASSWORD: easy-chat
    restart: always
    networks:
      easy-chat:
    user: "1000:1000"  # 添加当前用户的 UID 和 GID

networks:
  easy-chat:
    driver: bridge